/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.practica1.practica1.FrontEnd;

import com.practica1.practica1.FrontEnd.FrameEmpleados.InternalFrameEmpleados;
import com.practica1.practica1.FrontEnd.FrameInsumos.InternalFrameInsumos;
import com.practica1.practica1.FrontEnd.FrameProductos.InternalFrameProductos;

/**
 *
 * @author Kevin
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Principal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2 = new javax.swing.JInternalFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        crearCuentaItem = new javax.swing.JMenuItem();
        menúItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salirItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        empleadosItem = new javax.swing.JMenuItem();
        nóminaItem = new javax.swing.JMenuItem();
        inventarioItem = new javax.swing.JMenuItem();
        productosItem = new javax.swing.JMenuItem();
        mesasItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        reporteFlujoItem = new javax.swing.JMenuItem();
        reporteProductoItem = new javax.swing.JMenuItem();
        reporteInsumoItem = new javax.swing.JMenuItem();

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(160, 90));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        setResizable(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        crearCuentaItem.setText("Crear Cuenta");
        crearCuentaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaItemActionPerformed(evt);
            }
        });
        jMenu1.add(crearCuentaItem);

        menúItem.setText("Menú");
        jMenu1.add(menúItem);
        jMenu1.add(jSeparator1);

        salirItem.setText("Salir");
        salirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirItemActionPerformed(evt);
            }
        });
        jMenu1.add(salirItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listados");

        empleadosItem.setText("Empleados");
        empleadosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosItemActionPerformed(evt);
            }
        });
        jMenu2.add(empleadosItem);

        nóminaItem.setText("Nómina");
        jMenu2.add(nóminaItem);

        inventarioItem.setText("Inventario");
        inventarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioItemActionPerformed(evt);
            }
        });
        jMenu2.add(inventarioItem);

        productosItem.setText("Productos");
        productosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosItemActionPerformed(evt);
            }
        });
        jMenu2.add(productosItem);

        mesasItem.setText("Mesas");
        jMenu2.add(mesasItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        reporteFlujoItem.setText("Flujo de Caja");
        jMenu3.add(reporteFlujoItem);

        reporteProductoItem.setText("Productos más Vendidos");
        jMenu3.add(reporteProductoItem);

        reporteInsumoItem.setText("Insumos de Bajo Stock");
        jMenu3.add(reporteInsumoItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCuentaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCuentaItemActionPerformed

    private void empleadosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosItemActionPerformed
        InternalFrameEmpleados frame = new InternalFrameEmpleados();
        frame.setLocation((jDesktopPane1.getWidth() - 700) / 2, (jDesktopPane1.getHeight() - 415) / 2);
        jDesktopPane1.add(frame);
        jDesktopPane1.repaint();
    }//GEN-LAST:event_empleadosItemActionPerformed

    private void salirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirItemActionPerformed

    private void inventarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioItemActionPerformed
        InternalFrameInsumos frame = new InternalFrameInsumos();
        frame.setLocation((jDesktopPane1.getWidth() - 700) / 2, (jDesktopPane1.getHeight() - 415) / 2);
        jDesktopPane1.add(frame);
        jDesktopPane1.repaint();
    }//GEN-LAST:event_inventarioItemActionPerformed

    private void productosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosItemActionPerformed
        InternalFrameProductos frame = new InternalFrameProductos();
        frame.setLocation((jDesktopPane1.getWidth() - 750) / 2, (jDesktopPane1.getHeight() - 550) / 2);
        jDesktopPane1.add(frame);
        jDesktopPane1.repaint();
    }//GEN-LAST:event_productosItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem crearCuentaItem;
    private javax.swing.JMenuItem empleadosItem;
    private javax.swing.JMenuItem inventarioItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menúItem;
    private javax.swing.JMenuItem mesasItem;
    private javax.swing.JMenuItem nóminaItem;
    private javax.swing.JMenuItem productosItem;
    private javax.swing.JMenuItem reporteFlujoItem;
    private javax.swing.JMenuItem reporteInsumoItem;
    private javax.swing.JMenuItem reporteProductoItem;
    private javax.swing.JMenuItem salirItem;
    // End of variables declaration//GEN-END:variables
}
