/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameMesas;

import com.practica1.practica1.BackEnd.DataBase.MesaDB;
import com.practica1.practica1.BackEnd.Exceptions.DataBaseException;
import com.practica1.practica1.BackEnd.Exceptions.FormatoDatosException;
import com.practica1.practica1.BackEnd.Mesa.Mesa;
import com.practica1.practica1.BackEnd.Mesa.OperadorMesa;
import java.awt.BorderLayout;
import javax.swing.*;

/**
 *
 * @author kevinl
 */
public class InternalFrameMesas extends javax.swing.JInternalFrame {

    public MesaDB database;
    public OperadorMesa operador;

    /**
     * Creates new form InternalFrameMesas
     */
    public InternalFrameMesas() {
        initComponents();
        initFrame();
    }

    private void initFrame() {
        try {
            database = new MesaDB();
            operador = new OperadorMesa();
            cambiarALista();
            setVisible(true);
        } catch (DataBaseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void cambiarPanel(JPanel panel) {
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    public void cambiarALista() {
        PanelMesas panel = new PanelMesas(this);
        cambiarPanel(panel);
    }

    public void cambiarASeleccion() {
        try {
            Mesa[] mesas = database.pedirListado();
            if (mesas.length > 0) {
                PanelSeleccionMesa panel = new PanelSeleccionMesa(this, mesas);
                cambiarPanel(panel);
            } else {
                JOptionPane.showMessageDialog(this, "Agrege alguna mesa antes.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void cambiarADatos(String modo, Mesa mesa) {
        PanelDatosMesa panel = new PanelDatosMesa(this, modo, mesa);
        cambiarPanel(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
