/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameMesas;

import com.practica1.practica1.BackEnd.Exceptions.*;
import com.practica1.practica1.BackEnd.Mesa.Mesa;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinl
 */
public class PanelSeleccionMesa extends javax.swing.JPanel {

    private final InternalFrameMesas FRAME;
    private DefaultComboBoxModel modelo;

    /**
     * Creates new form PanelSeleccionMesa
     *
     * @param frame
     * @param mesas
     */
    public PanelSeleccionMesa(InternalFrameMesas frame, Mesa[] mesas) {
        FRAME = frame;
        crearTabla(mesas);
        initComponents();
    }

    private void crearTabla(Mesa[] mesas) {
        Object[] lista = FRAME.operador.convertirListaNumero(mesas);
        modelo = new DefaultComboBoxModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        capacidadField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        estadoField = new javax.swing.JTextField();
        selecionarButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione la mesa que quiere editar:");

        jLabel2.setText("Número De Mesa");

        numeroComboBox.setModel(modelo);
        numeroComboBox.addItemListener(this::numeroComboBoxItemStateChanged);

        jLabel3.setText("Capacidad De La Mesa");

        capacidadField.setEditable(false);
        capacidadField.setBackground(new java.awt.Color(255, 255, 255));
        capacidadField.setFocusable(false);

        jLabel4.setText("Estado De Ocupacion De La Mesa");

        estadoField.setEditable(false);
        estadoField.setBackground(new java.awt.Color(255, 255, 255));
        estadoField.setFocusable(false);

        selecionarButton.setText("Seleccionar");
        selecionarButton.addActionListener(this::selecionarButtonActionPerformed);

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(this::regresarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selecionarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(regresarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(numeroComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(capacidadField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capacidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionarButton)
                    .addComponent(regresarButton))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarButtonActionPerformed
        if (numeroComboBox.getSelectedIndex() != -1) {
            try {
                Mesa mesa = FRAME.database.pedirMesa((int) numeroComboBox.getSelectedItem());
                FRAME.cambiarADatos("Editar", mesa);
            } catch (DataBaseException | FormatoDatosException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione alguna mesa.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_selecionarButtonActionPerformed

    private void numeroComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_numeroComboBoxItemStateChanged
        if (numeroComboBox.getSelectedIndex() != -1) {
            try {
                Mesa mesa = FRAME.database.pedirMesa((int) numeroComboBox.getSelectedItem());
                capacidadField.setText(String.valueOf(mesa.getCapacidad()));
                estadoField.setText(mesa.getEstado().toString());
            } catch (DataBaseException | FormatoDatosException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            capacidadField.setText("");
            estadoField.setText("");
        }
    }//GEN-LAST:event_numeroComboBoxItemStateChanged

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        FRAME.cambiarALista();
    }//GEN-LAST:event_regresarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacidadField;
    private javax.swing.JTextField estadoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> numeroComboBox;
    private javax.swing.JButton regresarButton;
    private javax.swing.JButton selecionarButton;
    // End of variables declaration//GEN-END:variables
}
