/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameMesas;

import com.practica1.practica1.BackEnd.Exceptions.*;
import com.practica1.practica1.BackEnd.Mesa.Mesa;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinl
 */
public class PanelDatosMesa extends javax.swing.JPanel {

    private final InternalFrameMesas FRAME;
    private final String MODO;
    private int numeroAnterior;

    /**
     * Creates new form PanelDatosMesa
     *
     * @param frame
     * @param modo
     * @param mesa
     */
    public PanelDatosMesa(InternalFrameMesas frame, String modo, Mesa mesa) {
        FRAME = frame;
        MODO = modo;
        initComponents();
        initPanel(mesa);
    }

    private void initPanel(Mesa mesa) {
        switch (MODO) {
            case "Agregar" -> {
                jLabel1.setText("Llene los espacios para agregar una mesa:");
            }
            case "Editar" -> {
                numeroAnterior = mesa.getNumero();
                jLabel1.setText("Edite los campos disponible a cambiar en la mesa:");
                numeroField.setText(String.valueOf(mesa.getNumero()));
                capacidadField.setText(String.valueOf(mesa.getCapacidad()));
            }

        }
        accionButton.setText(MODO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accionButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroField = new javax.swing.JFormattedTextField();
        capacidadField = new javax.swing.JFormattedTextField();

        accionButton.setText("accion");
        accionButton.addActionListener(this::accionButtonActionPerformed);

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(this::regresarButtonActionPerformed);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("label");

        jLabel2.setText("Número De Mesa");

        jLabel3.setText("Capacidad De La Mesa");

        numeroField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        capacidadField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(accionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(regresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroField)
                                .addComponent(capacidadField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capacidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accionButton)
                    .addComponent(regresarButton))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionButtonActionPerformed
        try {
            Mesa mesa = new Mesa(Integer.parseInt(numeroField.getText()), Integer.parseInt(capacidadField.getText()), "LIBRE");
            switch (MODO) {
                case "Agregar" -> {
                    FRAME.operador.revisarNumero(FRAME.database, mesa);
                    FRAME.database.agregarMesa(mesa);
                    JOptionPane.showMessageDialog(this, "Se a agregado la mesa con exito.", "Completado", JOptionPane.OK_OPTION);
                }
                case "Editar" -> {
                    if (mesa.getNumero() != numeroAnterior) {
                        FRAME.operador.revisarNumero(FRAME.database, mesa);
                    }
                    FRAME.database.editarMesa(mesa, numeroAnterior);
                    JOptionPane.showMessageDialog(this, "Se a editado la mesa con exito.", "Completado", JOptionPane.OK_OPTION);
                }
            }
            FRAME.cambiarALista();
        } catch (DataBaseException | FormatoDatosException | DataExistenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionButtonActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        switch (MODO) {
            case "Agregar" ->
                FRAME.cambiarALista();
            case "Editar" ->
                FRAME.cambiarASeleccion();
        }
    }//GEN-LAST:event_regresarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accionButton;
    private javax.swing.JFormattedTextField capacidadField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField numeroField;
    private javax.swing.JButton regresarButton;
    // End of variables declaration//GEN-END:variables
}
