/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameProductos;

import com.practica1.practica1.BackEnd.DataBase.*;
import com.practica1.practica1.BackEnd.Exceptions.DataBaseException;
import com.practica1.practica1.BackEnd.Producto.*;
import com.practica1.practica1.BackEnd.Receta.*;
import java.awt.BorderLayout;
import javax.swing.*;

/**
 *
 * @author kevinl
 */
public class InternalFrameProductos extends javax.swing.JInternalFrame {

    public ProductoDB database;
    public OperadorProducto operador;
    public RecetaDB databaseReceta;
    public OperadorReceta operadorReceta;
    
    /**
     * Creates new form InternalFrameProductos
     */
    public InternalFrameProductos() {
        initComponents();
        initFrame();
    }

    private void initFrame() {
        try {
            database = new ProductoDB();
            databaseReceta = new RecetaDB();
            operador = new OperadorProducto();
            operadorReceta = new OperadorReceta();
            cambiarALista();
            setVisible(true);
        } catch (DataBaseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cambiarPanel(JPanel panelTemp) {
        panel.removeAll();
        panel.setLayout(new BorderLayout());
        panel.add(panelTemp);
        panel.revalidate();
        panel.repaint();
    }

    public void cambiarALista() {
        PanelProductos panelTemp = new PanelProductos(this);
        cambiarPanel(panelTemp);
    }

    public void cambiarASeleccion() {
        PanelSeleccionProducto panelTemp = new PanelSeleccionProducto(this);
        cambiarPanel(panelTemp);
    }

    public void cambiarADatos(String modo, Producto producto) {
        PanelDatosProducto panelTemp = new PanelDatosProducto(this, modo, producto);
        cambiarPanel(panelTemp);
    }

    public void cambiarAReceta(String modo, String modoProducto, Producto producto) {
        PanelInsumoReceta panelTemp = new PanelInsumoReceta(this, modo, modoProducto, producto);
        cambiarPanel(panelTemp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
