/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameProductos;

import com.practica1.practica1.BackEnd.DataBase.InsumoDB;
import com.practica1.practica1.BackEnd.Exceptions.*;
import com.practica1.practica1.BackEnd.Insumo.*;
import com.practica1.practica1.BackEnd.Producto.Producto;
import com.practica1.practica1.BackEnd.Receta.Receta;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinl
 */
public class PanelInsumoReceta extends javax.swing.JPanel {

    private final InternalFrameProductos FRAME;
    private final String MODO;
    private final String MODO_PRODUCTO;
    private final Producto PRODUCTO;
    private InsumoDB database;
    private OperadorInsumo operador;
    private DefaultComboBoxModel modelo;

    /**
     * Creates new form PanelInsumoReceta
     *
     * @param frame
     * @param modo
     * @param modoProducto
     * @param producto
     */
    public PanelInsumoReceta(InternalFrameProductos frame, String modo, String modoProducto, Producto producto) {
        FRAME = frame;
        MODO = modo;
        MODO_PRODUCTO = modoProducto;
        PRODUCTO = producto;
        createData();
        initComponents();
        initPanel();
    }

    private void createData() {
        try {
            database = new InsumoDB();
            operador = new OperadorInsumo();
            Object[] lista;
            if (MODO.equals("Agregar")) {
                Insumo[] insumos = database.pedirListado();
                lista = operador.convertirListaInsumosCodigo(insumos);
            } else {
                lista = FRAME.operadorReceta.convertirListaCodigo(PRODUCTO.getReceta());
            }
            modelo = new DefaultComboBoxModel(lista);
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initPanel() {
        switch (MODO) {
            case "Agregar" ->
                jLabel1.setText("Seleccione el insumo a agregar y escriba la cantidad a a utilizar:");
            case "Editar" ->
                jLabel1.setText("Seleccione el insumo a editar y modifiqué la cantidad a a utilizar:");
            case "Eliminar" -> {
                jLabel1.setText("Selecione el insumo a eliminar:");
                cantidadField.setEditable(false);
                cantidadField.setFocusable(false);
            }
        }
        accionButton.setText(MODO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        medidaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stockField = new javax.swing.JTextField();
        stockMinimoField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        costoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        codigoComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cantidadField = new javax.swing.JFormattedTextField();
        regresarButton = new javax.swing.JButton();
        accionButton = new javax.swing.JButton();

        jLabel3.setText("Unidad De Medida");

        jLabel7.setText("Nombre");

        medidaField.setEditable(false);
        medidaField.setBackground(new java.awt.Color(255, 255, 255));
        medidaField.setFocusable(false);

        jLabel4.setText("Stock");

        jLabel5.setText("Stock Mínimo");

        stockField.setEditable(false);
        stockField.setBackground(new java.awt.Color(255, 255, 255));
        stockField.setFocusable(false);

        stockMinimoField.setEditable(false);
        stockMinimoField.setBackground(new java.awt.Color(255, 255, 255));
        stockMinimoField.setFocusable(false);

        jLabel6.setText("Costo");

        costoField.setEditable(false);
        costoField.setBackground(new java.awt.Color(255, 255, 255));
        costoField.setFocusable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("label");

        jLabel2.setText("Codigo");

        nombreField.setEditable(false);
        nombreField.setBackground(new java.awt.Color(255, 255, 255));
        nombreField.setFocusable(false);

        codigoComboBox.setModel(modelo);
        codigoComboBox.addItemListener(this::codigoComboBoxItemStateChanged);

        jLabel8.setText("Cantidad");

        cantidadField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        cantidadField.setText("0.00");

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(this::regresarButtonActionPerformed);

        accionButton.setText("accion");
        accionButton.addActionListener(this::accionButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(medidaField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(codigoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(stockMinimoField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(costoField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombreField)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(accionButton)
                            .addGap(18, 18, 18)
                            .addComponent(regresarButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(cantidadField))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medidaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockMinimoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(accionButton))
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codigoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_codigoComboBoxItemStateChanged
        if (codigoComboBox.getSelectedIndex() != -1) {
            try {
                Insumo insumo = database.pedirInsumo((String) codigoComboBox.getSelectedItem());
                nombreField.setText(insumo.getNombre());
                medidaField.setText(insumo.getUnidadMedida());
                stockField.setText(String.valueOf(insumo.getStock()));
                stockMinimoField.setText(String.valueOf(insumo.getStockMinimo()));
                costoField.setText(String.valueOf(insumo.getCosto()));
                if (!MODO.equals("Agregar")) {
                    int index = codigoComboBox.getSelectedIndex() - 1;
                    String cantidadString = String.valueOf(PRODUCTO.getReceta()[index].getCantidad());
                    cantidadField.setText(cantidadString);
                } else {
                    cantidadField.setText("0.00");
                }
            } catch (DataBaseException | FormatoDatosException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            nombreField.setText("");
            medidaField.setText("");
            stockField.setText("");
            stockMinimoField.setText("");
            costoField.setText("");
            cantidadField.setText("0.00");
        }
    }//GEN-LAST:event_codigoComboBoxItemStateChanged

    private void accionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionButtonActionPerformed
        try {
            switch (MODO) {
                case "Agregar" ->
                    agregarInsumo();
                case "Editar" -> {
                    corroborarInsumo();
                    editarInsumo();
                }
                case "Eliminar" -> {
                    corroborarInsumo();
                    eliminarInsumo();
                }
            }
            FRAME.cambiarADatos(MODO_PRODUCTO, PRODUCTO);
        } catch (DataBaseException | FormatoDatosException | DataExistenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionButtonActionPerformed

    private void corroborarInsumo() throws DataBaseException, FormatoDatosException, DataExistenteException {
        Insumo insumo = database.pedirInsumo((String) codigoComboBox.getSelectedItem());
        if (!insumo.getNombre().equals(nombreField.getText())) {
            throw new DataExistenteException("El código seleccionado no coincide con el nombre seleccionado.");
        }
    }

    private void agregarInsumo() throws DataBaseException, DataExistenteException {
        String codigo = FRAME.operadorReceta.crearCodigo(PRODUCTO.getReceta(), FRAME.databaseReceta);
        Receta receta = new Receta(codigo, PRODUCTO.getCodigo(), (String) codigoComboBox.getSelectedItem(), nombreField.getText(),
                Integer.parseInt(cantidadField.getText()), medidaField.getText());
        PRODUCTO.agregarInsumo(receta);
    }

    private void editarInsumo() {
        int index = codigoComboBox.getSelectedIndex() - 1;
        PRODUCTO.getReceta()[index].setCantidad(Integer.parseInt(cantidadField.getText()));   
    }

    private void eliminarInsumo() throws DataBaseException {
        int index = codigoComboBox.getSelectedIndex() - 1;
        PRODUCTO.eliminarInsumo(index);   
    }

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        FRAME.cambiarADatos(MODO_PRODUCTO, PRODUCTO);
    }//GEN-LAST:event_regresarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accionButton;
    private javax.swing.JFormattedTextField cantidadField;
    private javax.swing.JComboBox<String> codigoComboBox;
    private javax.swing.JTextField costoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField medidaField;
    private javax.swing.JTextField nombreField;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTextField stockField;
    private javax.swing.JTextField stockMinimoField;
    // End of variables declaration//GEN-END:variables
}
