/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameProductos;

import com.practica1.practica1.BackEnd.Exceptions.*;
import com.practica1.practica1.BackEnd.Producto.Producto;
import javax.swing.*;

/**
 *
 * @author kevinl
 */
public class PanelProductos extends javax.swing.JPanel {

    private final String[] TITULOS = {"Código", "Nombre", "Categoria", "Precio"};
    private InternalFrameProductos frame;

    /**
     * Creates new form PanelProductos
     *
     * @param frame
     */
    public PanelProductos(InternalFrameProductos frame) {
        this.frame = frame;
        initComponents();
        initPanel();
    }

    private void initPanel() {
        try {
            Producto[] lista = frame.database.pedirListado();
            crearTabla(frame.operador.convertirListaProductos(lista));
            setVisible(true);
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void crearTabla(Object[][] datos) {
        JTable tabla = new JTable(datos, TITULOS);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setEnabled(false);
        panel.setViewportView(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarButton = new javax.swing.JButton();
        crearButton = new javax.swing.JButton();
        panel = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(738, 514));

        editarButton.setText("Editar Producto");
        editarButton.addActionListener(this::editarButtonActionPerformed);

        crearButton.setText("Crear Producto");
        crearButton.addActionListener(this::crearButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crearButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarButton)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton)
                    .addComponent(crearButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        frame.cambiarASeleccion();
    }//GEN-LAST:event_editarButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        frame.cambiarADatos("Crear", null);
    }//GEN-LAST:event_crearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JScrollPane panel;
    // End of variables declaration//GEN-END:variables
}
