/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameProductos;

import com.practica1.practica1.BackEnd.Exceptions.*;
import com.practica1.practica1.BackEnd.Producto.Producto;
import com.practica1.practica1.BackEnd.Receta.Receta;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author kevinl
 */
public class PanelDatosProducto extends javax.swing.JPanel {

    private final String[] TITULOS = {"Codigo Insumo", "Nombre Insumo", "Cantidad", "Unidad De Medida"};
    private InternalFrameProductos frame;
    private final String MODO;
    private Producto producto;

    /**
     * Creates new form PanelDatosProducto
     *
     * @param frame
     * @param modo
     * @param productoIn
     */
    public PanelDatosProducto(InternalFrameProductos frame, String modo, Producto productoIn) {
        this.frame = frame;
        MODO = modo;
        createData(productoIn);
        initComponents();
        initPanel();
        crearTabla();
    }

    private void createData(Producto productoIn) {
        try {
            if (productoIn == null) {
                producto = new Producto(frame.operador.crearCodigo(frame.database));
            } else {
                producto = productoIn;
            }
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initPanel() {
        switch (MODO) {
            case "Crear" ->
                label1.setText("Ingrese los datos del producto a crear:");
            case "Editar" ->
                label1.setText("Cambie los datos del producto a editar:");
        }
        nombreField.setText(producto.getNombre());
        CategoriaComboBox.setSelectedItem(producto.getCategoria().toString());
        precioField.setText(String.valueOf(producto.getPrecio()));
        accionButton.setText(MODO);
    }

    private void crearTabla() {
        Object[][] datos = frame.operadorReceta.convertirLista(producto.getReceta());
        JTable tabla = new JTable(datos, TITULOS);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setEnabled(false);
        scollPanel.setViewportView(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        CategoriaComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        precioField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        scollPanel = new javax.swing.JScrollPane();
        cancelarButton = new javax.swing.JButton();
        eliminarInsumoButton = new javax.swing.JButton();
        editarInsumoButton = new javax.swing.JButton();
        agregarInsumoButton = new javax.swing.JButton();
        accionButton = new javax.swing.JButton();

        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Label");

        jLabel1.setText("Nombre");

        jLabel2.setText("Categoria");

        jLabel3.setText("Precio");

        CategoriaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BEBIDA_CALIENTE", "BEBIDA_FRIA", "POSTRE", "COMIDA" }));

        jLabel4.setText("Q");

        precioField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        precioField.setText("0.00");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Receta Del Producto");

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(this::cancelarButtonActionPerformed);

        eliminarInsumoButton.setText("Eliminar Insumo");
        eliminarInsumoButton.addActionListener(this::eliminarInsumoButtonActionPerformed);

        editarInsumoButton.setText("Editar Insumo");
        editarInsumoButton.addActionListener(this::editarInsumoButtonActionPerformed);

        agregarInsumoButton.setText("Agregar Insumo");
        agregarInsumoButton.addActionListener(this::agregarInsumoButtonActionPerformed);

        accionButton.setText("accion");
        accionButton.addActionListener(this::accionButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarInsumoButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarInsumoButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarInsumoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accionButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombreField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addComponent(CategoriaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(precioField))))
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scollPanel)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(precioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarInsumoButton)
                    .addComponent(editarInsumoButton)
                    .addComponent(agregarInsumoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(accionButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarInsumoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInsumoButtonActionPerformed
        cambiarAReceta("Agregar");
    }//GEN-LAST:event_agregarInsumoButtonActionPerformed

    private void editarInsumoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarInsumoButtonActionPerformed
        cambiarAReceta("Editar");
    }//GEN-LAST:event_editarInsumoButtonActionPerformed

    private void eliminarInsumoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarInsumoButtonActionPerformed
        cambiarAReceta("Eliminar");
    }//GEN-LAST:event_eliminarInsumoButtonActionPerformed

    private void accionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionButtonActionPerformed
        try {
            guardarDatos();
            switch (MODO) {
                case "Crear" -> {
                    frame.database.agregarProducto(producto);
                    guardarRecetas();
                }
                case "Editar" -> {
                    frame.database.editarProducto(producto);
                    eliminarRecetas();
                    editarRecetas();
                }
            }
            frame.cambiarALista();
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionButtonActionPerformed

    private void guardarRecetas() throws DataBaseException {
        for (Receta receta : producto.getReceta()) {
            frame.databaseReceta.agregarReceta(receta);
        }
    }

    private void eliminarRecetas() throws DataBaseException, FormatoDatosException {
        Receta[] recetasExistentes = frame.operadorReceta.crearReceta(producto.getCodigo(), frame.databaseReceta);
        for (Receta receta : recetasExistentes) {
            if (!revisarReceta(receta.getCodigo(), producto.getReceta())) {
                frame.databaseReceta.eliminarReceta(receta.getCodigo());
            }
        }
    }

    private void editarRecetas() throws DataBaseException, FormatoDatosException {
        Receta[] recetasExistentes = frame.operadorReceta.crearReceta(producto.getCodigo(), frame.databaseReceta);
        for (Receta receta : producto.getReceta()) {
            if (revisarReceta(receta.getCodigo(), recetasExistentes)) {
                frame.databaseReceta.editarReceta(receta);
            } else {
                frame.databaseReceta.agregarReceta(receta);
            }
        }
    }

    private boolean revisarReceta(String codigo, Receta[] recetaARevisar) {
        for (Receta receta : recetaARevisar) {
            if (codigo.equals(receta.getCodigo())) {
                return true;
            }
        }
        return false;
    }

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        switch (MODO) {
            case "Crear" -> {
                frame.cambiarALista();
            }
            case "Editar" -> {
                frame.cambiarASeleccion();
            }
        }

    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void cambiarAReceta(String modo) {
        if (producto.getReceta().length == 0 && !modo.equals("Agregar")) {
            JOptionPane.showMessageDialog(this, "Ingrese algún insumo a la receta.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                guardarDatos();
                frame.cambiarAReceta(modo, MODO, producto);
            } catch (FormatoDatosException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void guardarDatos() throws FormatoDatosException {
        try {
            producto.setNombre(nombreField.getText());
            producto.setCategoria((String) CategoriaComboBox.getSelectedItem());
            producto.setPrecio(Double.parseDouble(precioField.getText()));
        } catch (NumberFormatException e) {
            throw new FormatoDatosException("Ingrese un numero de precio valido.");
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategoriaComboBox;
    private javax.swing.JButton accionButton;
    private javax.swing.JButton agregarInsumoButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton editarInsumoButton;
    private javax.swing.JButton eliminarInsumoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JFormattedTextField precioField;
    private javax.swing.JScrollPane scollPanel;
    // End of variables declaration//GEN-END:variables
}
