/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameProductos;

import com.practica1.practica1.BackEnd.Exceptions.DataBaseException;
import com.practica1.practica1.BackEnd.Exceptions.FormatoDatosException;
import com.practica1.practica1.BackEnd.Producto.Producto;
import com.practica1.practica1.BackEnd.Receta.Receta;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevinl
 */
public class PanelSeleccionProducto extends javax.swing.JPanel {

    private final InternalFrameProductos FRAME;
    private DefaultComboBoxModel modelo;

    /**
     * Creates new form PanelSeleccionProducto
     */
    public PanelSeleccionProducto(InternalFrameProductos frame) {
        FRAME = frame;
        createData();
        initComponents();
    }

    private void createData() {
        try {
            Producto[] productos = FRAME.database.pedirListado();
            Object[] lista = FRAME.operador.convertirListaProductosCodigo(productos);
            modelo = new DefaultComboBoxModel(lista);
        } catch (FormatoDatosException | DataBaseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        scollPanel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        categoriaField = new javax.swing.JTextField();
        precioField = new javax.swing.JTextField();
        codigoComboBox = new javax.swing.JComboBox<>();

        seleccionarButton.setText("Seleccionar");
        seleccionarButton.addActionListener(this::seleccionarButtonActionPerformed);

        jLabel4.setText("Q");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Receta Del Producto");

        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Seleccione el producto que quiere editar:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Insumo", "Nombre Insumo", "Cantidad", "Unidad De Medida"
            }
        ));
        scollPanel.setViewportView(jTable1);

        jLabel1.setText("Nombre");

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(this::cancelarButtonActionPerformed);

        jLabel2.setText("Categoria");

        jLabel3.setText("Precio");

        nombreField.setEditable(false);
        nombreField.setBackground(new java.awt.Color(255, 255, 255));
        nombreField.setFocusable(false);

        jLabel6.setText("Código");

        categoriaField.setEditable(false);
        categoriaField.setBackground(new java.awt.Color(255, 255, 255));
        categoriaField.setFocusable(false);

        precioField.setEditable(false);
        precioField.setBackground(new java.awt.Color(255, 255, 255));
        precioField.setFocusable(false);

        codigoComboBox.setModel(modelo);
        codigoComboBox.addItemListener(this::codigoComboBoxItemStateChanged);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seleccionarButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scollPanel)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombreField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoriaField)
                                .addComponent(codigoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(precioField))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label1)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(categoriaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(seleccionarButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarButtonActionPerformed
        /*try {
            guardarDatos();
            switch (MODO) {
                case "Crear" -> {
                    frame.database.agregarProducto(producto);
                    guardarReceta();
                }
                case "Editar" -> {
                    frame.database.editarProducto(producto);
                    editarReceta();
                }
            }
            frame.cambiarALista();
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_seleccionarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        FRAME.cambiarALista();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void codigoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_codigoComboBoxItemStateChanged
        if (codigoComboBox.getSelectedIndex() != -1) {
            try {
                Producto producto = FRAME.database.pedirProducto((String) codigoComboBox.getSelectedItem());
                producto.setRecetario(FRAME.operadorReceta.crearReceta(producto.getCodigo(), FRAME.databaseReceta));
                nombreField.setText(producto.getNombre());
                categoriaField.setText(producto.getCategoria().toString());
                precioField.setText(String.valueOf(producto.getPrecio()));
                CrearTabla(producto.getReceta());
            } catch (DataBaseException | FormatoDatosException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            nombreField.setText("");
            categoriaField.setText("");
            precioField.setText("");
            limpiarTabla();
        }
    }//GEN-LAST:event_codigoComboBoxItemStateChanged

    private void limpiarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
        jTable1.setModel(modeloTabla);
    }

    private void CrearTabla(Receta[] recetas) {
        limpiarTabla();
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
        for (Receta receta : recetas) {
            Object[] fila = {receta.getCodigoInsumo(), receta.getNombre(), receta.getCantidad(), receta.getUnidadDeMedida()};
            modeloTabla.addRow(fila);
        }
        jTable1.setModel(modeloTabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField categoriaField;
    private javax.swing.JComboBox<String> codigoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField precioField;
    private javax.swing.JScrollPane scollPanel;
    private javax.swing.JButton seleccionarButton;
    // End of variables declaration//GEN-END:variables
}
