/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameInsumos;

import com.practica1.practica1.BackEnd.CompraInsumo.*;
import com.practica1.practica1.BackEnd.DataBase.*;
import com.practica1.practica1.BackEnd.Exceptions.DataBaseException;
import com.practica1.practica1.BackEnd.Insumo.*;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kevinl
 */
public final class InternalFrameInsumos extends javax.swing.JInternalFrame {

    public InsumoDB database;
    public OperadorInsumo operador;
    public CompraInsumoDB databaseCompra;
    public OperadorCompraInsumo operadorCompra;

    /**
     * Creates new form InternalFrameInsumos
     */
    public InternalFrameInsumos() {
        initComponents();
        try {
            database = new InsumoDB();
            databaseCompra = new CompraInsumoDB();
            operador = new OperadorInsumo();
            operadorCompra = new OperadorCompraInsumo();
            cambiarALista();
            setVisible(true);
        } catch (DataBaseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cambiarPanel(JPanel panel) {
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public void cambiarALista() {
        PanelInsumos panel = new PanelInsumos(this);
        cambiarPanel(panel);
    }
    
    public void cambiarADatos(String modo, Insumo insumo){
        PanelDatosInsumo panel = new PanelDatosInsumo(this, modo, insumo);
        cambiarPanel(panel);
    }
    
    public void cambiarASeleccion() {
        PanelSeleccionInsumo panel = new PanelSeleccionInsumo(this);
        cambiarPanel(panel);
        
    }
    
    public void cambiarACompra(CompraInsumo compra) {
        PanelCompraInsumo panel = new PanelCompraInsumo(this, compra);
        cambiarPanel(panel);
        
    }
    
    public void cambiarADetalleCompra(CompraInsumo compra) {
        PanelDetalleCompra panel = new PanelDetalleCompra(this, compra);
        cambiarPanel(panel);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(700, 415));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
