/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameInsumos;

import BackEnd.Exceptions.*;
import BackEnd.Insumo.Insumo;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author kevinl
 */
public class PanelInsumos extends javax.swing.JPanel {

    private final String[] TITULOS = {"Código", "Nombre", "Unidad de medida", "Cantida de stock", "Stock mínimo", "Costo"};
    private InternalFrameInsumos frame;

    /**
     * Creates new form PanelInsumos
     */
    public PanelInsumos(InternalFrameInsumos frame) {
        this.frame = frame;
        initComponents();
        try {
            Insumo[] lista = frame.database.pedirListado();
            crearTabla(frame.operador.convertirListaInsumos(lista));
            setVisible(true);
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void crearTabla(Object[][] datos) {
        JTable tabla = new JTable(datos, TITULOS);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setEnabled(false);
        panel.setViewportView(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JScrollPane();
        editarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        compraButton = new javax.swing.JButton();

        editarButton.setText("Editar");
        editarButton.addActionListener(this::editarButtonActionPerformed);

        agregarButton.setText("Agregar");
        agregarButton.addActionListener(this::agregarButtonActionPerformed);

        compraButton.setText("Crear Compra");
        compraButton.addActionListener(this::compraButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(compraButton)
                        .addGap(18, 18, 18)
                        .addComponent(agregarButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarButton))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton)
                    .addComponent(agregarButton)
                    .addComponent(compraButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        frame.cambiarASeleccion();
    }//GEN-LAST:event_editarButtonActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        frame.cambiarADatos("Agregar", null);
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void compraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraButtonActionPerformed
        frame.cambiarACompra();
    }//GEN-LAST:event_compraButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton compraButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JScrollPane panel;
    // End of variables declaration//GEN-END:variables
}
