/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameInsumos;

import com.practica1.practica1.BackEnd.CompraInsumo.*;
import com.practica1.practica1.BackEnd.Exceptions.*;
import com.practica1.practica1.BackEnd.Insumo.Insumo;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevinl
 */
public class PanelCompraInsumo extends javax.swing.JPanel {

    private InternalFrameInsumos frame;
    private CompraInsumo compra;
    private final DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");


    /**
     * Creates new form PanelCompraInsumo
     * @param frame
     * @param compraInsumo
     */
    public PanelCompraInsumo(InternalFrameInsumos frame, CompraInsumo compraInsumo) {
        this.frame = frame;
        try {
            if (compraInsumo == null) {
                compra = new CompraInsumo(frame.operadorCompra.crearCodigoCompra(frame.databaseCompra));
            } else {
                compra = compraInsumo;
            }
        } catch (DataBaseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        crearTabla();
        fechaField.setText(compra.getFecha().format(formato));

    }

    public void crearTabla() {
        DetalleCompra[] detalleCompras = compra.getDetalleCompras();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        for (DetalleCompra detalleCompra : detalleCompras) {
            Object[] nuevaFila = {detalleCompra.getCodigoInsumo(), detalleCompra.getNombreInsumo(), detalleCompra.getCantidad(), detalleCompra.getCosto()};
            modelo.addRow(nuevaFila);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        panel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaField = new javax.swing.JFormattedTextField();
        agregarInsumoButton = new javax.swing.JButton();

        crearButton.setText("Crear Compra");
        crearButton.addActionListener(this::crearButtonActionPerformed);

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(this::cancelarButtonActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Insumo", "Nombre Insumo", "Cantidad", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panel.setViewportView(jTable1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalles de la Compra de Insumos");

        jLabel2.setText("Fecha de la compra");

        fechaField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        agregarInsumoButton.setText("Agregar Insumo");
        agregarInsumoButton.addActionListener(this::agregarInsumoButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregarInsumoButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(crearButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(cancelarButton))
                                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(agregarInsumoButton)))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(crearButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        frame.cambiarALista();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void agregarInsumoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInsumoButtonActionPerformed
        compra.setFecha(LocalDate.parse(fechaField.getText(), formato));
        frame.cambiarADetalleCompra(compra);
    }//GEN-LAST:event_agregarInsumoButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        try {
            compra.setFecha(LocalDate.parse(fechaField.getText(), formato));
            frame.databaseCompra.agregarCompraInsumo(compra);
            DetalleCompra[] detalles = compra.getDetalleCompras();
            for (DetalleCompra detalle : detalles) {
                agregarInsumoYDetalle(detalle);
            }
            JOptionPane.showMessageDialog(this, "Se a agregado la compra de insumos con exito.", "Completado", JOptionPane.OK_OPTION);
            frame.cambiarALista();
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_crearButtonActionPerformed

    private void agregarInsumoYDetalle(DetalleCompra detalleCompra) throws DataBaseException, FormatoDatosException {
        frame.databaseCompra.agregarDetalleCompra(detalleCompra);
        Insumo insumo = frame.database.pedirInsumo(detalleCompra.getCodigoInsumo());
        insumo.setStock(insumo.getStock() + detalleCompra.getCantidad());
        insumo.setCosto(detalleCompra.getCosto());
        frame.database.editarInsumo(insumo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarInsumoButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton crearButton;
    private javax.swing.JFormattedTextField fechaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane panel;
    // End of variables declaration//GEN-END:variables
}
