/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameInsumos;

import BackEnd.Exceptions.*;
import BackEnd.Insumo.Insumo;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinl
 */
public class PanelDetalleCompra extends javax.swing.JPanel {

    private InternalFrameInsumos frame;
    private PanelCompraInsumo panel;
    private DefaultComboBoxModel modelo;

    /**
     * Creates new form PanelDetalleCompra
     */
    public PanelDetalleCompra(InternalFrameInsumos frameIn, PanelCompraInsumo panelIn) {
        frame = frameIn;
        panel = panelIn;
        try {
            Insumo[] lista = frame.database.pedirListado();
            Object[] listado = frame.operador.convertirListaInsumosCodigo(lista);
            modelo = new DefaultComboBoxModel(listado);
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            frame.cambiarALista();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        medidaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        nombreField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codigoComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidadField = new javax.swing.JFormattedTextField();
        costoField = new javax.swing.JFormattedTextField();

        regresarButton2.setText("Regresar");
        regresarButton2.addActionListener(this::regresarButton2ActionPerformed);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Llene la información sobre el insumo a comprar:");

        medidaField.setEditable(false);
        medidaField.setBackground(new java.awt.Color(255, 255, 255));
        medidaField.setFocusable(false);

        jLabel2.setText("Código");

        editarButton.setText("Editar");
        editarButton.addActionListener(this::editarButtonActionPerformed);

        nombreField.setEditable(false);
        nombreField.setBackground(new java.awt.Color(255, 255, 255));
        nombreField.setFocusable(false);

        jLabel3.setText("Unidad De Medida");

        codigoComboBox.setModel(modelo);
        codigoComboBox.addItemListener(this::codigoComboBoxItemStateChanged);

        jLabel7.setText("Nombre");

        jLabel6.setText("Costo");

        jLabel4.setText("Cantidad");

        cantidadField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cantidadField.setText("0");

        costoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        costoField.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editarButton)
                                .addGap(18, 18, 18)
                                .addComponent(regresarButton2))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                    .addComponent(cantidadField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(medidaField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(costoField))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medidaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton2)
                    .addComponent(editarButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButton2ActionPerformed
        frame.cambiarPanel(panel);
    }//GEN-LAST:event_regresarButton2ActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        if (codigoComboBox.getSelectedIndex() != -1) {
            int cantidad = Integer.parseInt(cantidadField.getText());
            double costo = Double.parseDouble(costoField.getText());
            if (cantidad > 0 && costo > 0) {
                panel.agregarInsumo((String) codigoComboBox.getSelectedItem(), nombreField.getText(), cantidadField.getText(), costoField.getText());
                frame.cambiarPanel(panel);
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese una cantidad y/o costo mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione algún insumo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void codigoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_codigoComboBoxItemStateChanged
        if (codigoComboBox.getSelectedIndex() != -1) {
            try {
                Insumo insumo = frame.database.pedirInsumo((String) codigoComboBox.getSelectedItem());
                nombreField.setText(insumo.getNombre());
                medidaField.setText(insumo.getUnidadMedida());
            } catch (DataBaseException | FormatoDatosException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            nombreField.setText("");
            medidaField.setText("");
        }
    }//GEN-LAST:event_codigoComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cantidadField;
    private javax.swing.JComboBox<String> codigoComboBox;
    private javax.swing.JFormattedTextField costoField;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField medidaField;
    private javax.swing.JTextField nombreField;
    private javax.swing.JButton regresarButton;
    private javax.swing.JButton regresarButton1;
    private javax.swing.JButton regresarButton2;
    // End of variables declaration//GEN-END:variables
}
