/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameInsumos;

import com.practica1.practica1.BackEnd.Exceptions.*;
import com.practica1.practica1.BackEnd.Insumo.Insumo;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinl
 */
public class PanelDatosInsumo extends javax.swing.JPanel {

    private InternalFrameInsumos frame;
    private final String MODO;

    /**
     * Creates new form PanelDatosInsumo
     * @param frame
     * @param modo
     * @param insumo
     */
    public PanelDatosInsumo(InternalFrameInsumos frame, String modo, Insumo insumo) {
        this.frame = frame;
        MODO = modo;
        initComponents();
        switch (MODO) {
            case "Agregar" -> {
                jLabel2.setText("Llene los espacios para agregar un insumo:");
                jLabel1.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                codigoField.setVisible(false);
                stockField.setVisible(false);
                stockMinimoField.setVisible(false);
                costoField.setVisible(false);
            }
            case "Editar" -> {
                jLabel1.setText("Edite los campos disponible a cambiar en el insumo:");
                codigoField.setText(insumo.getCodigo());
                nombreField.setText(insumo.getNombre());
                medidaField.setText(insumo.getUnidadMedida());
                stockField.setText(String.valueOf(insumo.getStock()));
                stockMinimoField.setText(String.valueOf(insumo.getStockMinimo()));
                costoField.setText(String.valueOf(insumo.getCosto()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        medidaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stockField = new javax.swing.JTextField();
        stockMinimoField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        costoField = new javax.swing.JTextField();
        regresarButton = new javax.swing.JButton();
        actionButton = new javax.swing.JButton();
        nombreField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("label");

        jLabel2.setText("Codigo");

        codigoField.setEditable(false);
        codigoField.setBackground(new java.awt.Color(255, 255, 255));
        codigoField.setFocusable(false);

        jLabel3.setText("Unidad De Medida");

        jLabel4.setText("Stock");

        jLabel5.setText("Stock Mínimo");

        stockField.setEditable(false);
        stockField.setBackground(new java.awt.Color(255, 255, 255));
        stockField.setFocusable(false);

        jLabel6.setText("Costo");

        costoField.setEditable(false);
        costoField.setBackground(new java.awt.Color(255, 255, 255));
        costoField.setFocusable(false);

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(this::regresarButtonActionPerformed);

        actionButton.setText(MODO);
        actionButton.addActionListener(this::actionButtonActionPerformed);

        jLabel7.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codigoField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(medidaField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(actionButton)
                                .addGap(18, 18, 18)
                                .addComponent(regresarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(stockField))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(stockMinimoField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(costoField))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreField, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medidaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockMinimoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(actionButton))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed

        switch (MODO) {
            case "Agregar" ->
                frame.cambiarALista();
            case "Editar" ->
                frame.cambiarASeleccion();
        }
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        try {
            Insumo insumo;
            switch (MODO) {
                case "Agregar" -> {
                    String codigo = frame.operador.crearCodigo(frame.database);
                    insumo = new Insumo(codigo, nombreField.getText(), medidaField.getText(), 0, 0, 0);
                    frame.database.agregarInsumo(insumo);
                    JOptionPane.showMessageDialog(this, "Se a agregado el insumo con exito.", "Completado", JOptionPane.OK_OPTION);
                }
                case "Editar" -> {
                    insumo = new Insumo(codigoField.getText(), nombreField.getText(), medidaField.getText(), Integer.parseInt(stockField.getText()),
                            Integer.parseInt(stockMinimoField.getText()), Double.parseDouble(costoField.getText()));
                    frame.database.editarInsumo(insumo);
                    JOptionPane.showMessageDialog(this, "Se a editado el insumo con exito.", "Completado", JOptionPane.OK_OPTION);
                }
            }
            frame.cambiarALista();
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_actionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JTextField codigoField;
    private javax.swing.JTextField costoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField medidaField;
    private javax.swing.JTextField nombreField;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTextField stockField;
    private javax.swing.JTextField stockMinimoField;
    // End of variables declaration//GEN-END:variables
}
