/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameEmpleados;

import com.practica1.practica1.BackEnd.DataBase.EmpleadoDB;
import com.practica1.practica1.BackEnd.Empleado.Empleado;
import com.practica1.practica1.BackEnd.Empleado.OperadorEmpleado;
import com.practica1.practica1.BackEnd.Exceptions.*;
import java.awt.BorderLayout;
import javax.swing.*;

/**
 *
 * @author Kevin
 */
public class InternalFrameEmpleados extends javax.swing.JInternalFrame {

    public EmpleadoDB database;
    public OperadorEmpleado operador;

    /**
     * Creates new form InternalFrameEmpleados
     */
    public InternalFrameEmpleados() {
        initComponents();
        try {
            database = new EmpleadoDB();
            operador = new OperadorEmpleado();
            setVisible(true);
            cambiarALista();
        } catch (DataBaseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void cambiarALista() {
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());

        PanelEmpleados panel = new PanelEmpleados(this);
        jPanel1.add(panel, BorderLayout.CENTER);

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    public void cambiarADatos(String modo, Empleado empleado) {
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());

        PanelDatosEmpleado panel = new PanelDatosEmpleado(this, modo, empleado);
        jPanel1.add(panel, BorderLayout.CENTER);

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    public void cambiarASeleccion(String modo, Empleado[] lista) {
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());

        Object[] listado = operador.convertirListaEmpleadosDPI(lista);
        PanelSeleccionEmpleado panel = new PanelSeleccionEmpleado(this, modo, listado);
        jPanel1.add(panel, BorderLayout.CENTER);

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
