/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameEmpleados;

import BackEnd.Empleado.Empleado;
import BackEnd.Exceptions.*;
import javax.swing.*;

/**
 *
 * @author Kevin
 */
public class PanelEmpleados extends javax.swing.JPanel {

    private final String[] TITULOS = {"DPI", "Nombre", "Rol", "Jornada", "Salario", "Fecha de Contratación", "Estado"};
    private InternalFrameEmpleados frame;

    /**
     * Creates new form PanelEmpleados
     */
    public PanelEmpleados(InternalFrameEmpleados frame) {
        initComponents();
        this.frame = frame;
        try {
            Empleado[] lista = frame.database.pedirListado();

            crearTabla(frame.operador.convertirListaEmpleados(lista));
            setVisible(true);
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void crearTabla(Object[][] datos) {
        JTable tabla = new JTable(datos, TITULOS);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setEnabled(false);
        panel.setViewportView(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JScrollPane();
        habilitarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(676, 379));
        setMinimumSize(new java.awt.Dimension(676, 379));
        setPreferredSize(new java.awt.Dimension(676, 379));

        panel.setAutoscrolls(true);
        panel.setViewportView(null);

        habilitarButton.setText("Habilitar/Deshabilitar");
        habilitarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitarButtonActionPerformed(evt);
            }
        });

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarButton)
                .addGap(18, 18, 18)
                .addComponent(editarButton)
                .addGap(18, 18, 18)
                .addComponent(habilitarButton)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habilitarButton)
                    .addComponent(editarButton)
                    .addComponent(agregarButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        try {
            Empleado[] lista = frame.database.pedirListado();
            frame.cambiarASeleccion("Editar", lista);
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        frame.cambiarADatos("Agregar", null);
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void habilitarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarButtonActionPerformed
        try {
            Empleado[] lista = frame.database.pedirListado();
            frame.cambiarASeleccion("Habilitar", lista);
        } catch (DataBaseException | FormatoDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_habilitarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton habilitarButton;
    private javax.swing.JScrollPane panel;
    // End of variables declaration//GEN-END:variables
}
