/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.practica1.practica1.FrontEnd.FrameEmpleados;

import BackEnd.Empleado.Empleado;
import BackEnd.Exceptions.DataBaseException;
import BackEnd.Exceptions.FormatoDatosException;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class PanelSeleccionEmpleado extends javax.swing.JPanel {

    private InternalFrameEmpleados frame;
    private final String MODO;
    private DefaultComboBoxModel modelo;

    /**
     * Creates new form PanelSeleccionEmpleado
     */
    public PanelSeleccionEmpleado(InternalFrameEmpleados frame, String modo, Object[] listado) {
        this.frame = frame;
        MODO = modo;
        modelo = new DefaultComboBoxModel(listado);
        initComponents();
        switch (MODO) {
            case "Editar":
                jLabel1.setText("Seleccione el dpi del empleado que quiere editar:");
                accionButton.setText("Seleccionar");
                break;
            case "Habilitar":
                jLabel1.setText("Seleccione el dpi del empleado que quiere habilitar o deshabilitar:");
                accionButton.setText("Habilitar");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        rolField = new javax.swing.JTextField();
        rolField.setEditable(false);
        jLabel1 = new javax.swing.JLabel();
        jornadaField = new javax.swing.JTextField();
        jornadaField.setEditable(false);
        jComboBox1 = new javax.swing.JComboBox<>();
        fechaField = new javax.swing.JTextField();
        fechaField.setEditable(false);
        regresarButton = new javax.swing.JButton();
        salarioField = new javax.swing.JTextField();
        salarioField.setEditable(false);
        accionButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        nombreField.setEditable(false);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        estadoField = new javax.swing.JTextField();
        estadoField.setEditable(false);
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(676, 379));

        jLabel4.setText("Jornada laboral del empleado");

        rolField.setFocusable(false);
        rolField.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel1.setText("jLabel1");

        jornadaField.setFocusable(false);

        jComboBox1.setModel(modelo);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        fechaField.setFocusable(false);

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        salarioField.setFocusable(false);

        accionButton.setText("label");
        accionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Salario del empleado");

        jLabel7.setText("Fecha de contratación del empleado");

        nombreField.setFocusable(false);

        jLabel2.setText("Nombre Completo");

        jLabel3.setText("Rol del empleado");

        jLabel6.setText("Q");

        estadoField.setFocusable(false);

        jLabel8.setText("Estado de habilitación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(nombreField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(rolField, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jornadaField, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(accionButton)
                        .addGap(18, 18, 18)
                        .addComponent(regresarButton)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jornadaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(estadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(accionButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        frame.cambiarALista();
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void accionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionButtonActionPerformed
        if (jComboBox1.getSelectedIndex() != -1) {
            try {
                Empleado empleado = frame.database.pedirEmpleado((String) jComboBox1.getSelectedItem());
                switch (MODO) {
                    case "Editar" -> frame.cambiarADatos(MODO, empleado);
                    case "Habilitar" -> {
                        String mensaje = "El empleado seleccionado a sido ";
                        if (empleado.isHabilitado()) {
                            frame.database.cambiarEstado(empleado.getDpi(), false);
                            mensaje = mensaje + "deshabilitado exitosamente";
                        } else {
                            frame.database.cambiarEstado(empleado.getDpi(), true);
                            mensaje = mensaje + "habilitado exitosamente";
                        }
                        JOptionPane.showMessageDialog(this, mensaje, "Completo", JOptionPane.OK_OPTION);
                        frame.cambiarALista();
                    }
                }
            } catch (DataBaseException | FormatoDatosException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un número de DPI.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionButtonActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (jComboBox1.getSelectedIndex() != -1) {
            try {
                Empleado empleado = frame.database.pedirEmpleado((String) jComboBox1.getSelectedItem());
                nombreField.setText(empleado.getNombre());
                rolField.setText(empleado.getRol().toString());
                jornadaField.setText(empleado.getJornada().toString());
                salarioField.setText(String.valueOf(empleado.getSalario()));
                DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                fechaField.setText(empleado.getFechaContratacion().format(formato));
                if (empleado.isHabilitado()) {
                    estadoField.setText("Habilitado");
                    if (MODO.equals("Habilitar")) {
                        accionButton.setText("Deshabilitar");
                    }
                } else {
                    estadoField.setText("Deshabilitado");
                    if (MODO.equals("Habilitar")) {
                        accionButton.setText("Habilitar");
                    }
                }
            } catch (DataBaseException | FormatoDatosException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            nombreField.setText("");
            rolField.setText("");
            jornadaField.setText("");
            salarioField.setText("");
            fechaField.setText("");
            estadoField.setText("");
            if (MODO.equals("Habilitar")) {
                accionButton.setText("Habilitar");
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accionButton;
    private javax.swing.JTextField estadoField;
    private javax.swing.JTextField fechaField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jornadaField;
    private javax.swing.JTextField nombreField;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTextField rolField;
    private javax.swing.JTextField salarioField;
    // End of variables declaration//GEN-END:variables
}
